#!/usr/bin/env node

var ownership = require('./'),
    users = require('./crypto-users.json'),
    packages = require('./crypto-packages.json');

console.log('adding ' + users.length + ' owners to ' + packages.join(', '));

ownership.addUsersToPackages(users, packages, function(err) {
});
